
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package binario;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int uno = 3;
  public static final int error = 1;
  public static final int cero = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cero",
  "uno"
  };
}

