/* The following code was generated by JFlex 1.7.0 */

package compiladores_final;
import java_cup.runtime.Symbol;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import neoscript.p2.Interfaz;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>lexico.jflex</tt>
 */
public class AnalisisLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\25\1\26\1\71\1\25\1\25\22\0\1\25\1\53\1\65"+
    "\1\70\1\0\1\64\1\46\1\66\1\37\1\40\1\61\1\57\1\43"+
    "\1\60\1\2\1\62\12\1\1\44\1\45\1\55\1\54\1\56\1\47"+
    "\1\0\1\15\1\16\1\51\1\22\1\21\1\24\1\11\1\14\1\4"+
    "\2\3\1\20\1\3\1\5\1\17\2\3\1\10\1\7\1\6\1\23"+
    "\1\3\1\50\3\3\1\0\1\67\1\0\1\63\1\3\1\0\1\34"+
    "\1\16\1\12\1\22\1\32\1\33\1\11\1\13\1\4\2\3\1\35"+
    "\1\3\1\5\1\17\2\3\1\30\1\36\1\27\1\31\1\3\1\50"+
    "\3\3\1\41\1\52\1\42\7\0\1\71\u1fa2\0\1\71\1\71\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\11\3\1\4\2\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\2\3"+
    "\1\1\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\1\1\4\1\0\1\3\1\30"+
    "\12\3\1\31\1\3\1\32\1\33\2\0\1\34\1\0"+
    "\1\35\1\36\6\3\1\37\4\3\1\0\1\40\3\3"+
    "\1\41\1\3\1\42\1\3\1\4\1\3\1\43\2\3"+
    "\1\44\1\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\u0196"+
    "\0\u01d0\0\u020a\0\u0244\0\u027e\0\u02b8\0\u02f2\0\u032c\0\72"+
    "\0\72\0\72\0\72\0\72\0\72\0\72\0\u0366\0\72"+
    "\0\u03a0\0\u03da\0\u0414\0\72\0\u044e\0\72\0\72\0\72"+
    "\0\72\0\72\0\u0488\0\72\0\72\0\u04c2\0\u04fc\0\u0536"+
    "\0\u0570\0\u05aa\0\256\0\u05e4\0\u061e\0\u0658\0\u0692\0\u06cc"+
    "\0\u0706\0\u0740\0\u077a\0\u07b4\0\u07ee\0\72\0\u0828\0\72"+
    "\0\72\0\u0862\0\u04c2\0\72\0\u089c\0\u0570\0\256\0\u08d6"+
    "\0\u0910\0\u094a\0\u0984\0\u09be\0\u09f8\0\256\0\u0a32\0\u0a6c"+
    "\0\u0aa6\0\u0ae0\0\u0b1a\0\72\0\u0b54\0\u0b8e\0\u0bc8\0\256"+
    "\0\u0c02\0\256\0\u0c3c\0\72\0\u0c76\0\256\0\u0cb0\0\u0cea"+
    "\0\256\0\u0d24";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\2\4\1\6\2\4"+
    "\1\7\1\4\1\10\1\4\1\11\2\4\1\12\1\13"+
    "\1\4\1\14\2\15\1\16\2\4\1\12\1\17\2\4"+
    "\1\6\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\2\1\50\74\0\1\3\1\51\70\0\1\4"+
    "\1\0\22\4\2\0\10\4\11\0\2\4\21\0\1\4"+
    "\1\0\2\4\1\52\16\4\1\53\2\0\4\4\1\53"+
    "\3\4\11\0\2\4\21\0\1\4\1\0\3\4\1\54"+
    "\16\4\2\0\1\54\7\4\11\0\2\4\21\0\1\4"+
    "\1\0\10\4\2\55\3\4\1\56\4\4\2\0\6\4"+
    "\1\56\1\4\11\0\2\4\21\0\1\4\1\0\10\4"+
    "\2\55\10\4\2\0\10\4\11\0\2\4\21\0\1\4"+
    "\1\0\14\4\1\57\5\4\2\0\10\4\11\0\2\4"+
    "\21\0\1\4\1\0\15\4\1\60\4\4\2\0\6\4"+
    "\1\60\1\4\11\0\2\4\21\0\1\4\1\0\14\4"+
    "\1\61\5\4\2\0\10\4\11\0\2\4\21\0\1\4"+
    "\1\0\14\4\1\62\1\63\4\4\2\0\6\4\1\63"+
    "\1\4\11\0\2\4\45\0\2\15\44\0\1\4\1\0"+
    "\22\4\2\0\1\4\1\64\6\4\11\0\2\4\21\0"+
    "\1\4\1\0\14\4\1\62\1\63\4\4\2\0\5\4"+
    "\1\65\1\63\1\4\11\0\2\4\66\0\1\66\24\0"+
    "\1\4\1\0\10\4\2\67\10\4\2\0\10\4\11\0"+
    "\2\4\21\0\1\4\1\0\15\4\1\56\4\4\2\0"+
    "\6\4\1\56\1\4\11\0\2\4\72\0\1\70\73\0"+
    "\1\71\76\0\1\72\10\0\65\73\1\74\4\73\66\75"+
    "\2\0\2\75\26\50\1\0\43\50\1\0\1\76\71\0"+
    "\1\4\1\0\3\4\1\77\16\4\2\0\1\77\7\4"+
    "\11\0\2\4\21\0\1\4\1\0\5\4\1\100\14\4"+
    "\2\0\1\4\1\100\6\4\11\0\2\4\21\0\1\4"+
    "\1\0\12\4\1\101\7\4\2\0\5\4\1\101\2\4"+
    "\11\0\2\4\21\0\1\4\1\0\12\4\1\102\7\4"+
    "\2\0\5\4\1\102\2\4\11\0\2\4\21\0\1\4"+
    "\1\0\14\4\1\103\5\4\2\0\10\4\11\0\2\4"+
    "\21\0\1\4\1\0\4\4\1\104\15\4\2\0\7\4"+
    "\1\104\11\0\2\4\21\0\1\4\1\0\20\4\1\105"+
    "\1\4\2\0\2\4\1\105\5\4\11\0\2\4\21\0"+
    "\1\4\1\0\5\4\1\106\14\4\2\0\1\4\1\106"+
    "\6\4\11\0\2\4\21\0\1\4\1\0\14\4\1\107"+
    "\5\4\2\0\10\4\11\0\2\4\21\0\1\4\1\0"+
    "\22\4\2\0\2\4\1\110\5\4\11\0\2\4\21\0"+
    "\1\4\1\0\22\4\2\0\6\4\1\111\1\4\11\0"+
    "\2\4\21\0\1\4\1\0\1\4\1\112\20\4\2\0"+
    "\10\4\11\0\2\4\20\0\61\72\1\113\10\72\66\0"+
    "\1\114\4\0\1\4\1\0\1\4\1\115\20\4\2\0"+
    "\10\4\11\0\2\4\21\0\1\4\1\0\5\4\1\77"+
    "\14\4\2\0\1\4\1\77\6\4\11\0\2\4\21\0"+
    "\1\4\1\0\4\4\1\116\15\4\2\0\7\4\1\116"+
    "\11\0\2\4\21\0\1\4\1\0\15\4\1\117\4\4"+
    "\2\0\6\4\1\117\1\4\11\0\2\4\21\0\1\4"+
    "\1\0\16\4\1\120\3\4\2\0\3\4\1\120\4\4"+
    "\11\0\2\4\21\0\1\4\1\0\13\4\1\121\6\4"+
    "\2\0\10\4\11\0\2\4\21\0\1\4\1\0\12\4"+
    "\1\52\7\4\2\0\5\4\1\52\2\4\11\0\2\4"+
    "\21\0\1\4\1\0\22\4\2\0\3\4\1\122\4\4"+
    "\11\0\2\4\21\0\1\4\1\0\22\4\2\0\7\4"+
    "\1\110\11\0\2\4\21\0\1\4\1\0\15\4\1\123"+
    "\4\4\2\0\6\4\1\123\1\4\11\0\2\4\20\0"+
    "\61\72\1\113\1\124\7\72\1\0\1\4\1\0\2\4"+
    "\1\125\17\4\2\0\10\4\11\0\2\4\21\0\1\4"+
    "\1\0\16\4\1\126\3\4\2\0\3\4\1\126\4\4"+
    "\11\0\2\4\21\0\1\4\1\0\16\4\1\127\3\4"+
    "\2\0\3\4\1\127\4\4\11\0\2\4\21\0\1\4"+
    "\1\0\15\4\1\130\4\4\2\0\6\4\1\130\1\4"+
    "\11\0\2\4\21\0\1\4\1\0\16\4\1\131\3\4"+
    "\2\0\3\4\1\131\4\4\11\0\2\4\21\0\1\4"+
    "\1\0\6\4\1\77\13\4\2\0\10\4\11\0\2\4"+
    "\21\0\1\4\1\0\12\4\1\132\7\4\2\0\5\4"+
    "\1\132\2\4\11\0\2\4\21\0\1\4\1\0\16\4"+
    "\1\77\3\4\2\0\3\4\1\77\4\4\11\0\2\4"+
    "\21\0\1\4\1\0\2\4\1\77\17\4\2\0\10\4"+
    "\11\0\2\4\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3422];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\7\11\1\1\1\11\3\1\1\11"+
    "\1\1\5\11\1\1\2\11\3\1\1\0\14\1\1\11"+
    "\1\1\2\11\2\0\1\11\1\0\15\1\1\0\1\11"+
    "\7\1\1\11\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[90];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
//variables, metodos y funciones que necesite (codigo java)

  ComplexSymbolFactory symbolFactory;
  
  public void setSymbolFactory(ComplexSymbolFactory sf){
      symbolFactory = sf;
  }

  private Symbol symbol(String name, int sym) {
      return symbolFactory.newSymbol(name, sym, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+yylength(),yychar+yylength()));
  }

  private Symbol symbol(String name, int sym, Object val) {
      Location left = new Location(yyline+1,yycolumn+1,yychar);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private Symbol symbol(String name, int sym, Object val,int buflength) {
      Location left = new Location(yyline+1,yycolumn+yylength()-buflength,yychar+yylength()-buflength);
      Location right= new Location(yyline+1,yycolumn+yylength(), yychar+yylength());
      return symbolFactory.newSymbol(name, sym, left, right,val);
  }
  private void error(String message) {
    System.out.println("Error lexico en linea "+(yyline+1)+", columna "+(yycolumn+1)+" caracter: "+message);
    String errLex = "Error lexico en linea "+(yyline+1)+", columna "+(yycolumn+1)+" caracter: "+message;
    Interfaz.notificar_err(errLex);
  }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalisisLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 212) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {      return symbolFactory.newSymbol("EOF", Simbolo.EOF, new Location(yyline+1,yycolumn+1,yychar), new Location(yyline+1,yycolumn+1,yychar+1));
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error(yytext());
            } 
            // fall through
          case 37: break;
          case 2: 
            { return symbol("ENTERO",Simbolo.ENTERO, yytext());
            } 
            // fall through
          case 38: break;
          case 3: 
            { return symbol("ID",Simbolo.ID, yytext());
            } 
            // fall through
          case 39: break;
          case 4: 
            { 
            } 
            // fall through
          case 40: break;
          case 5: 
            { return symbol("PARENTESIS_ABIERTO",Simbolo.PARENTESIS_ABIERTO);
            } 
            // fall through
          case 41: break;
          case 6: 
            { return symbol("PARENTESIS_CERRADO",Simbolo.PARENTESIS_CERRADO);
            } 
            // fall through
          case 42: break;
          case 7: 
            { return symbol("LLAVE_ABIERTO",Simbolo.LLAVE_ABIERTO);
            } 
            // fall through
          case 43: break;
          case 8: 
            { return symbol("LLAVE_CERRADO",Simbolo.LLAVE_CERRADO);
            } 
            // fall through
          case 44: break;
          case 9: 
            { return symbol("COMA",Simbolo.COMA);
            } 
            // fall through
          case 45: break;
          case 10: 
            { return symbol("DOS_PUNTOS",Simbolo.DOS_PUNTOS);
            } 
            // fall through
          case 46: break;
          case 11: 
            { return symbol("PUNTO_COMA",Simbolo.PUNTO_COMA,yytext());
            } 
            // fall through
          case 47: break;
          case 12: 
            { return symbol("AMPERSAND",Simbolo.AMPERSAND);
            } 
            // fall through
          case 48: break;
          case 13: 
            { return symbol("TERNARIO",Simbolo.TERNARIO);
            } 
            // fall through
          case 49: break;
          case 14: 
            { return symbol("NOT",Simbolo.NOT);
            } 
            // fall through
          case 50: break;
          case 15: 
            { return symbol("IGUAL",Simbolo.IGUAL);
            } 
            // fall through
          case 51: break;
          case 16: 
            { return symbol("MENOR",Simbolo.MENOR);
            } 
            // fall through
          case 52: break;
          case 17: 
            { return symbol("MAYOR",Simbolo.MAYOR);
            } 
            // fall through
          case 53: break;
          case 18: 
            { return symbol("MAS",Simbolo.MAS);
            } 
            // fall through
          case 54: break;
          case 19: 
            { return symbol("MENOS",Simbolo.MENOS);
            } 
            // fall through
          case 55: break;
          case 20: 
            { return symbol("ASTERISCO",Simbolo.ASTERISCO);
            } 
            // fall through
          case 56: break;
          case 21: 
            { return symbol("SLASH",Simbolo.SLASH);
            } 
            // fall through
          case 57: break;
          case 22: 
            { return symbol("POTENCIA",Simbolo.POTENCIA);
            } 
            // fall through
          case 58: break;
          case 23: 
            { return symbol("MODULO",Simbolo.MODULO);
            } 
            // fall through
          case 59: break;
          case 24: 
            { return symbol("IF",Simbolo.IF);
            } 
            // fall through
          case 60: break;
          case 25: 
            { return symbol("AND",Simbolo.AND);
            } 
            // fall through
          case 61: break;
          case 26: 
            { return symbol("OR",Simbolo.OR);
            } 
            // fall through
          case 62: break;
          case 27: 
            { return symbol("IGUAL_IGUAL",Simbolo.IGUAL_IGUAL);
            } 
            // fall through
          case 63: break;
          case 28: 
            { String t = yytext();
                return symbol("CADENA",Simbolo.CADENA, t.substring(1, t.length() - 1));
            } 
            // fall through
          case 64: break;
          case 29: 
            { return symbol("DOUBLE",Simbolo.DOUBLE, yytext());
            } 
            // fall through
          case 65: break;
          case 30: 
            { return symbol("TIPO",Simbolo.TIPO,yytext());
            } 
            // fall through
          case 66: break;
          case 31: 
            { return symbol("FOR",Simbolo.FOR);
            } 
            // fall through
          case 67: break;
          case 32: 
            { String t = yytext();
                return symbol("CARACTER",Simbolo.CARACTER, t.substring(1, t.length() - 1));
            } 
            // fall through
          case 68: break;
          case 33: 
            { return symbol("ELSE",Simbolo.ELSE);
            } 
            // fall through
          case 69: break;
          case 34: 
            { return symbol("BOOLEANO",Simbolo.BOOLEANO, yytext());
            } 
            // fall through
          case 70: break;
          case 35: 
            { return symbol("CLASE",Simbolo.CLASE);
            } 
            // fall through
          case 71: break;
          case 36: 
            { return symbol("WHILE",Simbolo.WHILE);
            } 
            // fall through
          case 72: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
