
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package generacion3d;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int para = 32;
  public static final int opo = 17;
  public static final int caso = 26;
  public static final int opn = 18;
  public static final int seleccionar = 25;
  public static final int igualIgual = 3;
  public static final int allave = 12;
  public static final int numero = 7;
  public static final int imprimir = 30;
  public static final int mientras = 31;
  public static final int defecto = 28;
  public static final int pcoma = 20;
  public static final int sino = 9;
  public static final int por = 23;
  public static final int salir = 27;
  public static final int menos = 22;
  public static final int aparen = 10;
  public static final int cllave = 13;
  public static final int menor = 14;
  public static final int div = 24;
  public static final int igual = 19;
  public static final int EOF = 0;
  public static final int verdadero = 2;
  public static final int error = 1;
  public static final int cparen = 11;
  public static final int mas = 21;
  public static final int diferente = 4;
  public static final int dpuntos = 29;
  public static final int falso = 6;
  public static final int si = 8;
  public static final int opy = 16;
  public static final int mayor = 15;
  public static final int iden = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "verdadero",
  "igualIgual",
  "diferente",
  "iden",
  "falso",
  "numero",
  "si",
  "sino",
  "aparen",
  "cparen",
  "allave",
  "cllave",
  "menor",
  "mayor",
  "opy",
  "opo",
  "opn",
  "igual",
  "pcoma",
  "mas",
  "menos",
  "por",
  "div",
  "seleccionar",
  "caso",
  "salir",
  "defecto",
  "dpuntos",
  "imprimir",
  "mientras",
  "para"
  };
}

