
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package neoscript.p2;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CONCAT = 29;
  public static final int LLAVE_ABIERTO = 23;
  public static final int ENTERO = 41;
  public static final int SI = 5;
  public static final int CASE = 26;
  public static final int DOS_PUNTOS = 28;
  public static final int ENTONCES = 6;
  public static final int ASTERISCO = 39;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FOR = 21;
  public static final int HASTA = 14;
  public static final int SIGUIENTE = 16;
  public static final int NOT = 33;
  public static final int AND = 32;
  public static final int IGUAL = 37;
  public static final int FINMIENTRAS = 10;
  public static final int OR = 31;
  public static final int MIENTRAS = 9;
  public static final int PASO = 15;
  public static final int IF = 17;
  public static final int ID = 43;
  public static final int PUNTO_COMA = 40;
  public static final int IGUAL_IGUAL = 34;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 4;
  public static final int CADENA = 42;
  public static final int MENOR = 35;
  public static final int SWITCH = 25;
  public static final int MAYOR = 36;
  public static final int NO = 7;
  public static final int PUTS = 30;
  public static final int ELSE = 18;
  public static final int LLAVE_CERRADO = 24;
  public static final int WHILE = 20;
  public static final int DEFAULT = 27;
  public static final int HACER = 11;
  public static final int END = 19;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int PARA = 13;
  public static final int REPETIRMIENTRAS = 12;
  public static final int FINSI = 8;
  public static final int DO = 22;
  public static final int MAS = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "SI",
  "ENTONCES",
  "NO",
  "FINSI",
  "MIENTRAS",
  "FINMIENTRAS",
  "HACER",
  "REPETIRMIENTRAS",
  "PARA",
  "HASTA",
  "PASO",
  "SIGUIENTE",
  "IF",
  "ELSE",
  "END",
  "WHILE",
  "FOR",
  "DO",
  "LLAVE_ABIERTO",
  "LLAVE_CERRADO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DOS_PUNTOS",
  "CONCAT",
  "PUTS",
  "OR",
  "AND",
  "NOT",
  "IGUAL_IGUAL",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "ASTERISCO",
  "PUNTO_COMA",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

