
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package atributosheredados;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int floatT = 3;
  public static final int charT = 5;
  public static final int shortT = 7;
  public static final int longT = 8;
  public static final int id = 11;
  public static final int coma = 10;
  public static final int doubleT = 4;
  public static final int pcoma = 9;
  public static final int EOF = 0;
  public static final int intT = 6;
  public static final int error = 1;
  public static final int booleanT = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "booleanT",
  "floatT",
  "doubleT",
  "charT",
  "intT",
  "shortT",
  "longT",
  "pcoma",
  "coma",
  "id"
  };
}

